server:
  port: 8083
spring:
  data:
    redis:
      host: 127.0.0.1

xiequ:
  key: A
  refresh:
    key: B

config:
  locations:
    - name: work
      city-code: 510116
      latitude: 20.123456
      longitude: 10.123456
      price: 10
      rebate-price: 7
      dif-price: 5


